/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Apexcharts: typeof import('./src/components/plugins/Apexcharts.vue')['default']
    BFormTags: typeof import('bootstrap-vue-next')['BFormTags']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTooltip: typeof import('bootstrap-vue-next')['BTooltip']
    Card: typeof import('./src/components/bootstrap/Card.vue')['default']
    CardBody: typeof import('./src/components/bootstrap/CardBody.vue')['default']
    CardExpandToggler: typeof import('./src/components/bootstrap/CardExpandToggler.vue')['default']
    CardFooter: typeof import('./src/components/bootstrap/CardFooter.vue')['default']
    CardGroup: typeof import('./src/components/bootstrap/CardGroup.vue')['default']
    CardHeader: typeof import('./src/components/bootstrap/CardHeader.vue')['default']
    CardImgOverlay: typeof import('./src/components/bootstrap/CardImgOverlay.vue')['default']
    Chartjs: typeof import('./src/components/plugins/Chartjs.vue')['default']
    Datepicker: typeof import('./src/components/plugins/Datepicker.vue')['default']
    Footer: typeof import('./src/components/app/Footer.vue')['default']
    Header: typeof import('./src/components/app/Header.vue')['default']
    Highlightjs: typeof import('./src/components/plugins/Highlightjs.vue')['default']
    NavScrollTo: typeof import('./src/components/app/NavScrollTo.vue')['default']
    QuillEditor: typeof import('./src/components/plugins/QuillEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/app/Sidebar.vue')['default']
    SidebarNav: typeof import('./src/components/app/SidebarNav.vue')['default']
    TagsInput: typeof import('./src/components/plugins/TagsInput.vue')['default']
    ThemePanel: typeof import('./src/components/app/ThemePanel.vue')['default']
    Typeahead: typeof import('./src/components/plugins/Typeahead.vue')['default']
    VueSelect: typeof import('./src/components/plugins/VueSelect.vue')['default']
    VueTable: typeof import('./src/components/plugins/VueTable.vue')['default']
  }
}
